test_that("episode file vars match the vars list", {
  # These should be identical (names, order etc.)
  expect_identical(names(read_slf_episode("1415", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("1516", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("1617", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("1718", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("1819", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("1920", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("2021", from = 1, to = 1)), ep_file_vars)
  expect_identical(names(read_slf_episode("2122", from = 1, to = 1)), ep_file_vars)
})

test_that("individual file vars match the vars list", {
  # These should be identical (names, order etc.)
  expect_identical(names(read_slf_individual("1415", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("1516", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("1617", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("1718", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("1819", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("1920", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("2021", from = 1, to = 1)), indiv_file_vars)
  expect_identical(names(read_slf_individual("2122", from = 1, to = 1)), indiv_file_vars)
})
