on:
  push:
    paths:
      - 'README.Rmd'
  workflow_dispatch:
  
name: Render README

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
         use-public-rspm: true

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rmarkdown, local::.

      - name: Render README.Rmd
        run:  Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit the results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Render `README.md` after changes to the `.Rmd` version (GitHub action)
          file_pattern: README.md
          token: ${{ secrets.SLFHELPER_TOKEN_ADMIN }}
