on:
  push:
    paths:
      - 'README.Rmd'
  workflow_dispatch:
  
name: Render README

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
         use-public-rspm: true

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rmarkdown, local::.

      - name: Render README.Rmd
        run:  Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit and create a Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          add-paths: README.md
          commit-message: Render `README.md` after changes to the `.Rmd` version
          branch: render_readme
          delete-branch: true
          title: Automated re-knit of the README
          labels: documentation,Maintainance
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          
